notifications:
  email: false

language: android
jdk: oraclejdk8

env:
  matrix:
    - API=android-28 ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - sys-img-armeabi-v7a-android-28
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew clean assemble test

after_success:
  - ./gradlew :library:jacocoTestReport :library:coveralls
